// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CustomCursor() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"custom-cursor-dot\" class=\"fixed top-0 left-0 w-2.5 h-2.5 bg-blue-500 rounded-full pointer-events-none z-50 -translate-x-1/2 -translate-y-1/2 transition-transform duration-75 shadow-[0_0_12px_rgba(59,130,246,0.8)]\"></div><div id=\"custom-cursor-ring\" class=\"fixed top-0 left-0 w-8 h-8 border border-blue-400/40 rounded-full pointer-events-none z-50 -translate-x-1/2 -translate-y-1/2 transition-all duration-300 ease-out\"></div><script>\n\t\tdocument.addEventListener('DOMContentLoaded', () => {\n\t\t\tconst dot = document.getElementById('custom-cursor-dot');\n\t\t\tconst ring = document.getElementById('custom-cursor-ring');\n\t\t\tif (!dot || !ring) return;\n\n\t\t\tlet mouseX = -100, mouseY = -100;\n\t\t\tlet ringX = -100, ringY = -100;\n\n\t\t\twindow.addEventListener('mousemove', (e) => {\n\t\t\t\tmouseX = e.clientX;\n\t\t\t\tmouseY = e.clientY;\n\t\t\t\tdot.style.transform = `translate3d(${mouseX}px, ${mouseY}px, 0) translate(-50%, -50%)`;\n\t\t\t});\n\n\t\t\tconst renderRing = () => {\n\t\t\t\tringX += (mouseX - ringX) * 0.15;\n\t\t\t\tringY += (mouseY - ringY) * 0.15;\n\t\t\t\tring.style.transform = `translate3d(${ringX}px, ${ringY}px, 0) translate(-50%, -50%)`;\n\t\t\t\trequestAnimationFrame(renderRing);\n\t\t\t};\n\t\t\trenderRing();\n\n\t\t\tdocument.querySelectorAll('button, a, input, select, textarea, .clickable').forEach(el => {\n\t\t\t\tel.addEventListener('mouseenter', () => {\n\t\t\t\t\tring.classList.add('scale-150', 'border-blue-400', 'bg-blue-500/10');\n\t\t\t\t});\n\t\t\t\tel.addEventListener('mouseleave', () => {\n\t\t\t\t\tring.classList.remove('scale-150', 'border-blue-400', 'bg-blue-500/10');\n\t\t\t\t});\n\t\t\t});\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
